### ISSUE TITLE
Chinadns ng更新了，luci有计划更新吗？

### ISSUE THREAD

**Issue by jliveusa** [izilzty/luci-app-chinadns-ng#2]
更新加入了许多新特性，luci有跟进计划吗？

**Comment by izilzty** [comment]
你好，这两天我抽时间看一下，因为这个初始版本我也是克隆过来的，如果要大改的话比较费时间，如果修改比较简单的话我会把新功能加上。

**Comment by izilzty** [comment]
修改了一下，增加了对新功能的支持，如果测试没有其他问题，您可以关闭此Issues。

**Comment by jliveusa** [comment]
感谢更新，初步测试OK，就是不兼容openwrt23.05版本，语言文件无法生成，无法显示操作界面。

**Comment by jliveusa** [comment]
感谢更新，测试暂时无问题，就差一个自动更新列表的功能了，大佬可否参考一下https://github.com/NagaseKouichi/openwrt-chinadns-ng/tree/luci的实现过程

**Comment by izilzty** [comment]
我看现在chinadns-ng在安装的时候已经会自动创建一条自动更新的计划任务了 https://github.com/pexcn/openwrt-chinadns-ng/blob/b6fc5a419983fd832a9cc271642c839c6c502ad0/Makefile#L63C1-L63C1 默认时间是凌晨3:10，想要修改时间的话直接在 系统->计划任务 里修改就可以了。

**Comment by jliveusa** [comment]
文档提到fair-mode 从2023.03.06版本开始，只有公平模式，指不指定都一样。可以删除公平模式啦

**Comment by izilzty** [comment]
留着主要是为了兼容老版本的chinadns-ng，而且新版的chinadns-ng也没有删除这个开关，只是调整为了无作用，应该也是为了兼容。

不过可以改一下说明文字，这样更清楚。

**Comment by jliveusa** [comment]
openwrt 23.05中第一次启用时，保存应用后需要无法自动运行，需手动在启动项中启动才会运行。

**Comment by izilzty** [comment]
试一下用这个修改好的chinadns-ng包：https://github.com/izilzty/openwrt-chinadns-ng.git ，里面添加了一个触发器用来在配置更改时重启服务。
如果想用现在已经安装好的包可以手动编辑 `/etc/init.d/chinadns-ng`，将下面的代码添加到文件最后：
```
service_triggers() {
        procd_add_reload_trigger "chinadns-ng"
}
```
之后保存文件并手动重启一下chinadns-ng的服务或者重启系统就可以了。

**Comment by jliveusa** [comment]
openwrt-chinadns-ng中使用的是ipset，支持nft的family名@table名@set名 格式，之前没注意，导致日志反复出错，改成ipset格式后就正常了。

**Comment by jliveusa** [comment]
大佬，遇到个问题求解，chinadns-ng 与科学上网配合使用时，因科学域名在国外，无法获得外网IP，实现外网解析。能否在luci界面上添加选择框，自定义国内及国外路由表，强制科学域名用国内DNS解析呢，感谢~！

**Comment by izilzty** [comment]
这个可以用脚本在每天更新黑白名单以后自动执行一下，在 gfwlist.txt 里面把你要在国内解析的域名删掉，然后把这个域名添加到 chnlist.txt 里，最后重启一下 chinadns-ng 。如果在界面上提供了编辑的选项，最终还是会被自动更新覆盖掉的。

**Comment by jliveusa** [comment]
是比较麻烦，不知道能不能支持两个国内路由表，这样就能避免自动更新覆盖掉了

**Comment by izilzty** [comment]
chinadns-ng 可以支持，用逗号分隔开多个文件就可以了，例如：`/etc/chinadns-ng/chinalist.txt,/etc/chinadns-ng/mylist.txt`。
但是界面上因为检查了输入数据类型，所以之前不支持用逗号分隔。我已经修改了，去掉类数据型检查。
还有一点要注意一下，如果一个域名同时出现在 chinalist 和 gfwlist 里，那默认是用可信 dns 来解析，如果要用国内 dns 来解析的话要启用`国内路由表优先`

**Comment by jliveusa** [comment]
大佬，上游更新了10.28版本，新增了v4 v6共监听~~
